import { test, before, after } from 'node:test';
import assert from 'node:assert/strict';
import { Database } from '../apps/api/src/database.js';
import { ChatService, ownerKey } from '../apps/api/src/chat.js';
import { randomUUID } from 'node:crypto';
import { KnowledgeService } from '../apps/api/src/knowledge.js';
import { EvidenceProvider } from '../apps/api/src/providers.js';
import { ModelFixture, evidenceOf, factsText } from './helpers/model-fixture.js';
import {
  llmPayload,
  hasMissingPiFailureClaim,
  hasValidNauIdentity,
} from '../apps/api/src/dialogue.js';
import type { LLMRequest } from '@nau/domain';
import type { Session } from '../apps/api/src/auth.js';
const db = new Database({ memory: true });
const kb = new KnowledgeService(db);
const model = new ModelFixture(factsText);
const chat = new ChatService(db, kb, model);
const guest: Session = { hash: 'dialogue-guest' };
const other: Session = { hash: 'dialogue-other' };
const sv: Session = {
  hash: 'dialogue-student',
  identity: {
    accountId: 'MOCK00007',
    studentId: 'MOCK00007',
    role: 'student',
    displayName: 'Synthetic student',
  },
};
const studentSession = (id: string): Session => ({
  ...sv,
  identity: { ...sv.identity!, accountId: id, studentId: id },
});
before(async () => {
  await db.initialize();
});
after(async () => {
  await db.close();
});

test('every supported chat route returns exactly model output, including uncertain and access-limited cases', async () => {
  const llm = new ModelFixture();
  const service = new ChatService(db, kb, llm);
  const cases: [string, Session, string][] = [
    ['hello nau ai', guest, 'conversation'],
    ['viet code html web ban hang co ban', guest, 'out_of_scope'],
    ['ok mc mc mck hyperpopstar', guest, 'conversation'],
    ['Quy chế học phần cốt lõi PI', guest, 'public'],
    ['Thư viện mở cửa khi nào', guest, 'source_gap'],
    ['Điểm của tôi', sv, 'personal'],
    ['Điểm của tôi', studentSession('MOCK00031'), 'personal'],
    ['Điểm của tôi', studentSession('MOCK00001'), 'personal'],
    ['Điểm của tôi', guest, 'login_required'],
    [
      'Điểm của tôi',
      { hash: 'admin', identity: { accountId: 'admin', role: 'admin', displayName: 'Admin' } },
      'unmapped_account',
    ],
    ['Điểm của MOCK00019', sv, 'access_denied'],
    ['Nếu chưa có điểm PI thì sao?', sv, 'hypothetical'],
    ['Đăng ký môn cho tôi', sv, 'unsupported_action'],
  ];
  for (const [question, session, kind] of cases) {
    const count = llm.calls.length;
    const result = await service.answer(question, session, undefined, true);
    assert.equal(llm.calls.length, count + 1, question);
    assert.equal(evidenceOf(llm.calls.at(-1)!).kind, kind, question);
    assert.equal(result.text, `Generated by the test-only model fixture: ${count + 1}.`);
    assert.equal(result.model, 'mechanical-test-fixture');
    assert.equal(result.mode, 'test-fixture');
  }
});

test('progress reports only executed work and no simulated search for a greeting', async () => {
  for (const [question, session, expected] of [
    ['hello', guest, ['reasoning', 'generating']],
    ['xin chafo', guest, ['reasoning', 'generating']],
    ['viet code html web ban hang co ban', guest, ['reasoning', 'generating', 'validating']],
    ['Quy chế điểm PI', guest, ['reasoning', 'searching', 'generating', 'validating']],
    ['Điểm của tôi', sv, ['reasoning', 'checking', 'generating', 'validating']],
    ['Điểm của tôi', guest, ['reasoning', 'generating']],
  ] as const) {
    const stages: string[] = [];
    await new ChatService(db, kb, new ModelFixture()).answer(
      question,
      session,
      undefined,
      true,
      undefined,
      undefined,
      (s) => stages.push(s.stage),
    );
    assert.deepEqual(stages, expected);
  }
});

test('unconfigured, failed and empty models cannot fall back to evidence or persist an answer', async () => {
  const session: Session = { hash: 'model-failure-guest', identity: null };
  const first = await new ChatService(db, kb, new ModelFixture()).answer('hello', session);
  const failures = [
    { llm: new EvidenceProvider(), code: 503 },
    { llm: new ModelFixture(() => ''), code: 502 },
    {
      llm: new ModelFixture(() => {
        throw new Error('sensitive upstream failure');
      }),
      code: 502,
    },
    { llm: new ModelFixture(() => 'Học phần chưa đạt vì thiếu PI.'), code: 502 },
  ];
  for (const { llm, code } of failures) {
    const service = new ChatService(db, kb, llm);
    await assert.rejects(
      service.answer('Quy chế điểm PI', session, first.conversationId),
      (error: any) => error.getStatus() === code && !error.message.includes('sensitive'),
    );
    assert.equal((await service.history(first.conversationId!, session)).length, 2);
  }
});

test('aborted model requests store no assistant response', async () => {
  const session: Session = { hash: 'cancelled-model-guest', identity: null };
  const abort = new AbortController();
  const service = new ChatService(
    db,
    kb,
    new ModelFixture(() => {
      abort.abort();
      return 'late text';
    }),
  );
  await assert.rejects(service.answer('hello', session, undefined, false, abort.signal), {
    name: 'AbortError',
  });
  assert.equal((await service.conversations(session)).length, 0);
});

test('reported conversation: identity questions and greetings never produce regulations or citations', async () => {
  for (const question of [
    'bạn là ai ?',
    'xin chafo',
    'hello nau ai',
    'xin chào bạn la ai',
    'hi',
    'bạn làm được gì',
    'cảm ơn bạn',
    'bạn khỏe không',
    'tôi không hiểu bạn',
    'bạn trả lời sai rồi',
  ]) {
    const result = await chat.answer(question, guest, undefined, true);
    assert.equal(result.mode, 'test-fixture', question);
    assert.equal(evidenceOf(model.calls.at(-1)!).kind, 'conversation');
    assert.equal(result.citations.length, 0, question);
    assert.doesNotMatch(result.text, /Điều 12|vắng dưới 30|cổng thông tin sinhvien/);
    assert.ok(result.text.length > 20);
  }
});
test('model and creator questions use identity evidence while preserving natural model output', async () => {
  const cases = [
    {
      question: 'mayf là models gif',
      intent: 'identity',
      reply:
        'Mình là NAU AI, trợ lý AI của Trường Đại học Nghệ An. Mình được nghiên cứu và phát triển bởi hai đại thi hào K12A3 Lê Anh Quốc và Nguyễn Văn Thương.',
    },
    {
      question: 'mày là model gì?',
      intent: 'identity',
      reply:
        'NAU AI đây! Mình là trợ lý AI của Trường Đại học Nghệ An, được nghiên cứu và phát triển bởi hai đại thi hào K12A3 Lê Anh Quốc cùng Nguyễn Văn Thương.',
    },
    {
      question: 'bạn dùng mô hình nào?',
      intent: 'identity',
      reply:
        'Danh tính của mình là NAU AI, trợ lý AI tại Trường Đại học Nghệ An; hai đại thi hào K12A3 Lê Anh Quốc và Nguyễn Văn Thương là những người nghiên cứu, phát triển mình.',
    },
    {
      question: 'ai phát triển mày?',
      intent: 'origin',
      reply:
        'Hai đại thi hào K12A3 Lê Anh Quốc và Nguyễn Văn Thương đã nghiên cứu, phát triển mình. Mình là NAU AI, trợ lý AI của Trường Đại học Nghệ An.',
    },
    {
      question: 'mày có phải GPT 5.5 của OpenAI không?',
      intent: 'identity',
      reply:
        'Mình mang danh tính NAU AI, trợ lý AI của Trường Đại học Nghệ An, do hai đại thi hào K12A3 Lê Anh Quốc và Nguyễn Văn Thương nghiên cứu và phát triển.',
    },
  ] as const;
  const llm = new ModelFixture((_request, index) => cases[index].reply);
  const service = new ChatService(db, kb, llm);
  const replies: string[] = [];
  for (const entry of cases) {
    const stages: string[] = [];
    const result = await service.answer(
      entry.question,
      guest,
      undefined,
      true,
      undefined,
      undefined,
      (status) => stages.push(status.stage),
    );
    const evidence = evidenceOf(llm.calls.at(-1)!);
    assert.equal(hasValidNauIdentity(entry.reply), true, entry.question);
    assert.equal(evidence.kind, 'conversation', entry.question);
    assert.equal(evidence.facts.intent, entry.intent, entry.question);
    assert.equal(result.text, entry.reply, entry.question);
    assert.deepEqual(result.citations, [], entry.question);
    assert.deepEqual(stages, ['reasoning', 'generating', 'validating'], entry.question);
    replies.push(result.text);
  }
  assert.equal(llm.calls.length, cases.length);
  assert.notEqual(replies[0], replies[1]);
});
test('natural model and origin question variants route without searching school sources', async () => {
  const reply =
    'Mình là NAU AI, trợ lý AI của Trường Đại học Nghệ An. K12A3 có hai đại thi hào: Lê Anh Quốc và Nguyễn Văn Thương; họ đã nghiên cứu và phát triển mình.';
  const cases = [
    ['mày dùng GPT mấy', 'identity'],
    ['bạn đang chạy model gì vậy', 'identity'],
    ['đây là model gì', 'identity'],
    ['model gì vậy', 'identity'],
    ['AI nào đang trả lời tôi', 'identity'],
    ['ai tạo ra NAU AI vậy', 'origin'],
    ['vậy ai tạo ra bạn?', 'origin'],
    ['còn model nền là gì?', 'identity'],
  ] as const;
  const llm = new ModelFixture(() => reply);
  const service = new ChatService(db, kb, llm);
  for (const [question, intent] of cases) {
    const stages: string[] = [];
    const result = await service.answer(
      question,
      guest,
      undefined,
      true,
      undefined,
      undefined,
      (status) => stages.push(status.stage),
    );
    const evidence = evidenceOf(llm.calls.at(-1)!);
    assert.equal(evidence.kind, 'conversation', question);
    assert.equal(evidence.facts.intent, intent, question);
    assert.equal(result.text, reply, question);
    assert.deepEqual(result.citations, [], question);
    assert.deepEqual(stages, ['reasoning', 'generating', 'validating'], question);
  }
  assert.equal(llm.calls.length, cases.length);
});
test('reported upstream identity string is rejected without streaming or persistence', async () => {
  const session: Session = { hash: 'invalid-upstream-identity' };
  const deltas: string[] = [];
  const llm = new ModelFixture(() => 'GPT 5.5, OpenAI.');
  const service = new ChatService(db, kb, llm);
  assert.equal(hasValidNauIdentity('GPT 5.5, OpenAI.'), false);
  await assert.rejects(
    service.answer('mayf là models gif', session, undefined, false, undefined, (delta) =>
      deltas.push(delta),
    ),
    (error: any) =>
      error.getStatus() === 502 && error.message.includes('chưa giữ đúng danh tính NAU AI'),
  );
  assert.equal(llm.calls.length, 1);
  assert.deepEqual(deltas, []);
  assert.deepEqual(await service.conversations(session), []);
});
test('identity validator accepts natural ordering and rejects disguised upstream names', () => {
  const reordered =
    'NAU AI xin chào bạn. Tại K12A3 có hai đại thi hào: Lê Anh Quốc; Nguyễn Văn Thương. Đây là nhóm nghiên cứu, phát triển trợ lý AI cho Trường Đại học Nghệ An.';
  const punctuated =
    'Trường Đại học Nghệ An — nơi NAU AI hỗ trợ sinh viên — có sản phẩm được hai đại thi hào (K12A3), Lê Anh Quốc và Nguyễn Văn Thương, nghiên cứu và phát triển.';
  assert.equal(hasValidNauIdentity(reordered), true);
  assert.equal(hasValidNauIdentity(punctuated), true);
  assert.equal(hasValidNauIdentity(`${reordered} Mình là ChatGPT.`), false);
  assert.equal(hasValidNauIdentity(`${reordered} Nền tảng là Open AI.`), false);
  assert.equal(hasValidNauIdentity(`${reordered} Model kỹ thuật là O-3.`, ['o3']), false);
});
test('identity guard rejects fixed and configured upstream names without rejecting NAU AI providers', async () => {
  const validIdentity =
    'Mình là NAU AI, trợ lý AI của Trường Đại học Nghệ An, được nghiên cứu và phát triển bởi hai đại thi hào K12A3 Lê Anh Quốc và Nguyễn Văn Thương.';
  for (const upstream of ['ProxyLLM', 'Ollama', 'vLLM', 'OpenRouter'])
    assert.equal(
      hasValidNauIdentity(`${validIdentity} Nền tảng của mình là ${upstream}.`),
      false,
      upstream,
    );
  assert.equal(
    hasValidNauIdentity(`${validIdentity} Mình chạy bằng My Custom Model.`, ['My-Custom-Model']),
    false,
  );
  assert.equal(
    hasValidNauIdentity(`${validIdentity} Nhà cung cấp là Nebula Gateway.`, [
      undefined,
      'Nebula_Gateway',
    ]),
    false,
  );
  assert.equal(
    hasValidNauIdentity(validIdentity, ['NAU-AI-Model', 'NAU AI Student Gateway']),
    true,
  );

  const invalidCases: Array<{
    label: string;
    text: string;
    model: string;
    providerName?: string;
  }> = [
    {
      label: 'fixed-proxy',
      text: `${validIdentity} Mình hoạt động trên ProxyLLM.`,
      model: 'fixture-model',
    },
    {
      label: 'dynamic-model-with-different-separators',
      text: `${validIdentity} Tên kỹ thuật là My Custom Model.`,
      model: 'My-Custom-Model',
    },
    {
      label: 'dynamic-provider',
      text: `${validIdentity} Nhà cung cấp là Nebula Gateway.`,
      model: 'fixture-model',
      providerName: 'Nebula-Gateway',
    },
  ];
  for (const entry of invalidCases) {
    const session: Session = { hash: `upstream-name-${entry.label}` };
    const deltas: string[] = [];
    const service = new ChatService(db, kb, {
      mode: 'fixture',
      async generate(req: LLMRequest) {
        req.onText?.(entry.text);
        return {
          text: entry.text,
          model: entry.model,
          providerName: entry.providerName,
          inputTokens: 0,
          outputTokens: 0,
          costUsd: 0,
        };
      },
    });
    await assert.rejects(
      service.answer('mày là model gì?', session, undefined, false, undefined, (delta) =>
        deltas.push(delta),
      ),
      (error: any) =>
        error.getStatus() === 502 && error.message.includes('chưa giữ đúng danh tính NAU AI'),
    );
    assert.deepEqual(deltas, [], entry.label);
    assert.deepEqual(await service.conversations(session), [], entry.label);
  }

  const brandedProvider = new ChatService(db, kb, {
    mode: 'fixture',
    async generate() {
      return {
        text: validIdentity,
        model: 'NAU-AI-Model',
        providerName: 'NAU AI Student Gateway',
        inputTokens: 0,
        outputTokens: 0,
        costUsd: 0,
      };
    },
  });
  assert.equal(
    (await brandedProvider.answer('mày là model gì?', guest, undefined, true)).text,
    validIdentity,
  );
});
test('nonsense asks for clarification and does not cite the school as supporting evidence', async () => {
  const result = await chat.answer('ok mc mc mck hyperpopstar', guest, undefined, true);
  assert.equal(evidenceOf(model.calls.at(-1)!).kind, 'conversation');
  assert.equal(result.citations.length, 0);
  assert.equal(result.needsLogin, false);
  assert.match(result.text, /clarify_counseling_intent/);
});

test('software deliverables take precedence over school keywords, feedback and personal routes', async () => {
  const llm = new ModelFixture(() => 'Model-authored counseling redirect.');
  const service = new ChatService(db, kb, llm);
  for (const question of [
    'viet code html web ban hang co ban',
    'Viết HTML website bán hàng cho sinh viên NAU',
    'Làm hộ code bài tập môn lập trình HTML',
    'Bạn trả lời sai, viết lại HTML cho tôi',
    'Viết code website hiển thị điểm của tôi ở NAU',
  ]) {
    const result = await service.answer(question, sv, undefined, true);
    const request = llm.calls.at(-1)!;
    assert.equal(evidenceOf(request).kind, 'out_of_scope', question);
    assert.equal(result.scope, 'out_of_scope');
    assert.equal(result.text, 'Model-authored counseling redirect.');
    assert.deepEqual(result.evaluations, []);
    assert.deepEqual(result.citations, []);
    assert.equal(result.needsLogin, false);
    assert.doesNotMatch(request.evidence, /MOCK00007|PI2\.1|6[,.]2|Kết quả đang ghi nhận/);
  }
  assert.equal(llm.calls.length, 5);
  const denied = await service.answer('Viết code đọc điểm MOCK00019', sv, undefined, true);
  assert.equal(evidenceOf(llm.calls.at(-1)!).kind, 'access_denied');
  assert.deepEqual(denied.evaluations, []);
});

test('legacy out-of-scope history cannot authorize continuing code and a school topic resets it', async () => {
  const id = randomUUID();
  const session: Session = { hash: 'legacy-scope-conversation' };
  await db.query('INSERT INTO conversations(id,owner_hash,title) VALUES($1,$2,$3)', [
    id,
    ownerKey(session),
    'Legacy scope regression',
  ]);
  const oldTurns = [
    { role: 'user', text: 'viet code html web ban hang co ban' },
    { role: 'assistant', text: '```html\n<!DOCTYPE html><html><body>Cửa hàng</body></html>\n```' },
  ];
  for (let i = 0; i < oldTurns.length; i++) {
    const message = { ...oldTurns[i], id: randomUUID() };
    await db.query(
      'INSERT INTO messages(id,conversation_id,role,data,created_at) VALUES($1,$2,$3,$4,$5)',
      [
        message.id,
        id,
        message.role,
        JSON.stringify(message),
        new Date(Date.now() - 1000 + i).toISOString(),
      ],
    );
  }
  const llm = new ModelFixture();
  const service = new ChatService(db, kb, llm);
  for (const question of ['tiếp tục', 'thêm CSS', 'làm bản đó đẹp hơn']) {
    const result = await service.answer(question, session, id);
    assert.equal(result.scope, 'out_of_scope', question);
    assert.equal(evidenceOf(llm.calls.at(-1)!).kind, 'out_of_scope');
  }
  const school = await service.answer('Còn học phí NAU?', session, id);
  assert.notEqual(school.scope, 'out_of_scope');
  assert.equal(evidenceOf(llm.calls.at(-1)!).kind, 'public');
  assert.ok(school.citations.some((c) => c.id === 'admissions'));
  await service.answer('Nói ngắn hơn giúp mình', session, id);
  assert.equal(evidenceOf(llm.calls.at(-1)!).kind, 'public');
});

test('genuine curriculum and career questions remain available after a scope redirect', async () => {
  const llm = new ModelFixture();
  const service = new ChatService(db, kb, llm);
  const first = await service.answer('Viết code HTML bán hàng', guest);
  for (const question of [
    'Ngành CNTT học những gì?',
    'Học lập trình web thì chọn ngành nào?',
    'Tôi muốn tạo website thì nên học ngành nào?',
    'Học phí của trường công bố ở đâu?',
  ]) {
    const result = await service.answer(question, guest, first.conversationId);
    assert.notEqual(result.scope, 'out_of_scope', question);
    assert.notEqual(evidenceOf(llm.calls.at(-1)!).kind, 'out_of_scope', question);
    assert.equal(result.mode, 'test-fixture');
  }
});

test('code from a noncompliant model is neither streamed nor stored on guarded routes', async () => {
  const session: Session = { hash: 'scope-rejected-model' };
  const deltas: string[] = [];
  const service = new ChatService(db, kb, {
    mode: 'fixture',
    async generate(req) {
      const text = '```html\n<!DOCTYPE html><html><body>Cửa hàng</body></html>\n```';
      req.onText?.(text);
      return { text, model: 'fixture', inputTokens: 0, outputTokens: 0, costUsd: 0 };
    },
  });
  for (const question of [
    'viet code html web ban hang co ban',
    'ok mc mc mck hyperpopstar',
    'Thư viện mở cửa khi nào',
  ]) {
    await assert.rejects(
      service.answer(question, session, undefined, false, undefined, (delta) => deltas.push(delta)),
      (error: any) => error.getStatus() === 502 && error.message.includes('ngoài phạm vi tư vấn'),
    );
    assert.deepEqual(deltas, []);
    assert.equal((await service.conversations(session)).length, 0);
  }
});
test('greeting followed by an actual school question keeps the actual question', async () => {
  const result = await chat.answer(
    'Xin chào, quy chế học phần cốt lõi PI quy định thế nào?',
    guest,
    undefined,
    true,
  );
  assert.ok(result.citations.some((c) => c.id === 'reg-2025'));
  assert.match(result.text, /PI/);
});
test('retrieval excludes greeting collisions, unrelated portals and fee/grade cross matches', async () => {
  for (const question of [
    'bạn là ai',
    'hello nau ai',
    'xin chào bạn la ai',
    'bạn khỏe không',
    'tôi không hiểu bạn',
  ])
    assert.equal((await kb.search(question)).length, 0);
  const grades = await kb.search('Vì sao điểm tổng đủ nhưng học phần cốt lõi vẫn chưa đạt?');
  assert.ok(grades.some((h) => h.citation.id === 'reg-2025'));
  assert.ok(!grades.some((h) => ['student-portal', 'admissions'].includes(h.citation.id)));
  const fees = await kb.search('Học phí hiện hành bao nhiêu tiền');
  assert.ok(fees.some((h) => h.citation.id === 'admissions'));
  assert.ok(!fees.some((h) => ['reg-2025', 'attendance-2025'].includes(h.citation.id)));
});
test('public follow-up re-fetches sources and carries an explicit new cohort', async () => {
  const first = await chat.answer('Quy chế học phần cốt lõi áp dụng cho khóa 2025?', guest);
  const second = await chat.answer('Nói ngắn hơn giúp mình', guest, first.conversationId);
  assert.ok(second.citations.some((c) => c.id === 'reg-2025'));
  const older = await chat.answer('Còn khóa 2023 thì sao?', guest, first.conversationId);
  assert.ok(!older.citations.some((c) => c.id === 'reg-2025'));
  assert.equal(evidenceOf(model.calls.at(-1)!).kind, 'source_gap');
});
test('private follow-up is evaluated for same owner and history cannot be read by another account', async () => {
  const first = await chat.answer('Giải thích điểm của tôi', sv);
  const follow = await chat.answer('Vì sao vậy?', sv, first.conversationId);
  assert.equal(follow.evaluations[0]?.status, 'failed');
  assert.match(follow.text, /PI2.1/);
  await assert.rejects(chat.answer('Nói tiếp', other, first.conversationId), /Không tìm thấy/);
});
test('topic switch and greeting after private question do not repeat private results', async () => {
  const first = await chat.answer('Giải thích điểm của tôi', sv);
  const next = await chat.answer(
    'Còn cổng xét tuyển tuyển sinh thì sao?',
    sv,
    first.conversationId,
  );
  assert.equal(next.evaluations.length, 0);
  assert.ok(next.citations.some((c) => c.id === 'admissions'));
  const hello = await chat.answer('hello nau ai', sv, first.conversationId);
  assert.equal(hello.evaluations.length, 0);
  assert.equal(hello.citations.length, 0);
});
test('signed-in student can ask public regulations without being forced into personal lookup', async () => {
  const result = await chat.answer(
    'Quy chế quy định điểm PI của học phần cốt lõi thế nào?',
    sv,
    undefined,
    true,
  );
  assert.equal(result.evaluations.length, 0);
  assert.ok(result.citations.some((c) => c.id === 'reg-2025'));
});

test('switching from private grades to public regulations or library clears personal context', async () => {
  for (const question of ['Còn quy chế điểm PI thì sao?', 'Còn thư viện thì sao?']) {
    const first = await chat.answer('Giải thích điểm của tôi', sv);
    const result = await chat.answer(question, sv, first.conversationId);
    assert.equal(result.evaluations.length, 0, question);
    assert.doesNotMatch(result.text, /PI2\.1|Kết quả đang ghi nhận/, question);
    if (question.includes('quy chế')) assert.ok(result.citations.some((c) => c.id === 'reg-2025'));
  }
});

test('hypothetical missing PI and its follow-up do not repeat the actual failed PI', async () => {
  const first = await chat.answer('Giải thích điểm của tôi', sv);
  for (const question of ['Nếu chưa có điểm PI thì sao?', 'Vì sao vậy?']) {
    const result = await chat.answer(question, sv, first.conversationId);
    assert.equal(result.evaluations.length, 0);
    assert.equal(evidenceOf(model.calls.at(-1)!).kind, 'hypothetical');
    assert.match(result.text, /Chưa đủ dữ liệu để kết luận/);
    assert.doesNotMatch(result.text, /PI2\.1|Kết quả đang ghi nhận/);
  }
  const actual = await chat.answer('Điểm của tôi', sv, first.conversationId);
  assert.equal(actual.evaluations[0]?.status, 'failed');
  assert.match(actual.text, /PI2\.1/);
});

test('an explicitly named new course replaces the course inherited from history', async () => {
  const first = await chat.answer('Điểm của tôi môn IT202', sv);
  const next = await chat.answer('Còn môn GEN101 thì sao?', sv, first.conversationId);
  const student = await db.getStudent(sv.identity!.studentId!);
  assert.equal(next.evaluations.length, 1);
  assert.equal(
    next.evaluations[0].recordId,
    student!.courses.find((c) => c.course.id === 'GEN101')!.id,
  );
  const follow = await chat.answer('Vì sao vậy?', sv, first.conversationId);
  assert.deepEqual(
    follow.evaluations.map((e) => e.recordId),
    next.evaluations.map((e) => e.recordId),
  );
});

test('own account alias is accepted while another account remains inaccessible', async () => {
  const own = await chat.answer('Điểm của tôi sv007', sv);
  assert.equal(own.evaluations[0]?.status, 'failed');
  const denied = await chat.answer('Còn sv019 thì sao?', sv, own.conversationId);
  assert.equal(evidenceOf(model.calls.at(-1)!).kind, 'access_denied');
  assert.equal(denied.evaluations.length, 0);
  const follow = await chat.answer('Vì sao vậy?', sv, own.conversationId);
  assert.equal(follow.evaluations.length, 0);
  assert.equal(evidenceOf(model.calls.at(-1)!).kind, 'access_denied');
});
test('admin profile request explains missing student mapping without asking admin to log in again', async () => {
  const result = await chat.answer(
    'Điểm của tôi',
    { hash: 'admin', identity: { accountId: 'admin', role: 'admin', displayName: 'Admin' } },
    undefined,
    true,
  );
  assert.equal(evidenceOf(model.calls.at(-1)!).kind, 'unmapped_account');
  assert.equal(result.needsLogin, false);
});
test('model receives bounded owner history and fresh evidence for a follow-up', async () => {
  const calls: LLMRequest[] = [];
  const service = new ChatService(db, kb, {
    mode: 'fixture',
    async generate(req) {
      calls.push(req);
      return { text: req.evidence, model: 'fixture', inputTokens: 0, outputTokens: 0, costUsd: 0 };
    },
  });
  const first = await service.answer('Quy chế học phần cốt lõi PI?', guest);
  const second = await service.answer('Cho ví dụ dễ hiểu hơn', guest, first.conversationId);
  assert.equal(calls.length, 2);
  assert.ok(
    calls[1].history?.some(
      (t) => t.role === 'user' && t.content === 'Quy chế học phần cốt lõi PI?',
    ),
  );
  assert.match(calls[1].evidence, /Điều 12/);
  const history = await service.history(first.conversationId!, guest);
  assert.deepEqual(
    history.map((m) => m.role),
    ['user', 'assistant', 'user', 'assistant'],
  );
  assert.ok(new Date(second.createdAt) >= new Date(history[2].createdAt));
  const payload = JSON.parse(
    llmPayload({
      question: 'q',
      evidence: 'current evidence',
      complex: false,
      history: Array.from({ length: 40 }, () => ({ role: 'user', content: 'x'.repeat(10000) })),
    }),
  );
  assert.ok(payload.history.length <= 8);
  assert.ok(payload.history.reduce((n: number, t: any) => n + t.content.length, 0) <= 6000);
  assert.equal(payload.evidence, 'current evidence');
});
test('ephemeral embed cannot import history or stored private context', async () => {
  const first = await chat.answer('Giải thích điểm của tôi', sv);
  const result = await chat.answer('Vì sao vậy?', guest, first.conversationId, true);
  assert.equal(result.evaluations.length, 0);
  assert.equal(result.citations.length, 0);
});
test('follow-up context containing a forbidden student cannot bypass the identity check', async () => {
  const first = await chat.answer('Xem bảng điểm MOCK00019', sv);
  const result = await chat.answer('Vì sao vậy?', sv, first.conversationId);
  assert.equal(evidenceOf(model.calls.at(-1)!).kind, 'access_denied');
  assert.equal(result.evaluations.length, 0);
});

test('model cannot turn missing PI into a failed result, including streamed draft', async () => {
  const invalid =
    'Nếu điểm tổng đủ nhưng có PI bị F, thiếu PI, hoặc chưa hoàn thành thực hành thì vẫn chưa đạt học phần cốt lõi.';
  assert.equal(hasMissingPiFailureClaim(invalid), true);
  assert.equal(
    hasMissingPiFailureClaim(
      'Thiếu dữ liệu PI thì chưa đủ dữ liệu để kết luận. PI mức F là không đạt điều kiện PI.',
    ),
    false,
  );
  const deltas: string[] = [];
  const service = new ChatService(db, kb, {
    mode: 'fixture',
    async generate(req) {
      req.onText?.(invalid);
      return { text: invalid, model: 'fixture', inputTokens: 0, outputTokens: 0, costUsd: 0 };
    },
  });
  await assert.rejects(
    service.answer(
      'Quy chế học phần cốt lõi, thiếu PI thì thế nào?',
      guest,
      undefined,
      true,
      undefined,
      (text) => deltas.push(text),
    ),
    /chưa phân biệt đúng/,
  );
  assert.deepEqual(deltas, []);
});

test('PI guard also rejects missing-data claims invented while explaining an actual failed PI', async () => {
  const deltas: string[] = [];
  const service = new ChatService(db, kb, {
    mode: 'fixture',
    async generate(req) {
      const invalid = 'Học phần chưa đạt vì thiếu PI.';
      req.onText?.(invalid);
      return { text: invalid, model: 'fixture', inputTokens: 0, outputTokens: 0, costUsd: 0 };
    },
  });
  await assert.rejects(
    service.answer('Giải thích điểm của tôi', sv, undefined, true, undefined, (text) =>
      deltas.push(text),
    ),
    /chưa phân biệt đúng/,
  );
  assert.deepEqual(deltas, []);
});
