import { after, before, test } from 'node:test';
import assert from 'node:assert/strict';
import { STUDENT_FAQ_CATEGORIES, STUDENT_FAQ_QUESTIONS } from '@nau/domain';
import { Database } from '../apps/api/src/database.js';
import { ChatService } from '../apps/api/src/chat.js';
import { KnowledgeService } from '../apps/api/src/knowledge.js';
import { resolveQuestion } from '../apps/api/src/dialogue.js';
import { ModelFixture, evidenceOf } from './helpers/model-fixture.js';
import type { Session } from '../apps/api/src/auth.js';

const db = new Database({ memory: true });
const kb = new KnowledgeService(db);
const guest: Session = { hash: 'faq-guest' };
const student: Session = {
  hash: 'faq-student',
  identity: {
    accountId: 'MOCK00007',
    studentId: 'MOCK00007',
    role: 'student',
    displayName: 'Synthetic student',
  },
};
before(() => db.initialize());
after(() => db.close());

test('FAQ catalog covers every student topic without using prewritten answers', async () => {
  assert.equal(new Set(STUDENT_FAQ_QUESTIONS.map((q) => q.id)).size, STUDENT_FAQ_QUESTIONS.length);
  for (const group of STUDENT_FAQ_CATEGORIES) {
    assert.ok(STUDENT_FAQ_QUESTIONS.filter((q) => q.categoryId === group.id).length >= 5);
  }
  const model = new ModelFixture();
  const chat = new ChatService(db, kb, model);
  for (const entry of STUDENT_FAQ_QUESTIONS) {
    const answer = await chat.answer(entry.question, guest, undefined, true);
    const evidence = evidenceOf(model.calls.at(-1)!);
    assert.equal(answer.text, `Generated by the test-only model fixture: ${model.calls.length}.`);
    assert.equal(answer.needsLogin, entry.dataScope === 'personal', entry.id);
    assert.ok(
      entry.dataScope === 'personal'
        ? evidence.kind === 'login_required'
        : ['public', 'source_gap'].includes(evidence.kind),
      `${entry.id}: ${evidence.kind}`,
    );
  }
});

test('public procedural questions stay public even for logged-in students', async () => {
  const model = new ModelFixture();
  const chat = new ChatService(db, kb, model);
  const paraphrases = [
    'Xem lịch học ở đâu?',
    'Điểm rèn luyện được tính thế nào?',
    'Em muốn xin giấy xác nhận sinh viên thì liên hệ đâu?',
    'Em muốn hủy môn thì cần thủ tục gì?',
    'Làm thế nào để xin miễn giảm học phí?',
    'Nộp đơn phúc khảo ở đâu?',
    'Quên mật khẩu LMS thì làm sao?',
    'Học phí hiện hành bao nhiêu tiền?',
  ];
  for (const question of [
    ...STUDENT_FAQ_QUESTIONS.filter((q) => q.dataScope === 'public').map((q) => q.question),
    ...paraphrases,
  ]) {
    const answer = await chat.answer(question, student, undefined, true);
    const call = model.calls.at(-1)!;
    assert.ok(['public', 'source_gap'].includes(evidenceOf(call).kind), question);
    assert.equal(answer.evaluations.length, 0, question);
    assert.equal(answer.needsLogin, false, question);
    assert.equal(call.sensitivity, 'public');
    assert.ok(!call.evidence.includes('MOCK00007'), question);
  }
});

test('student services retrieve their verified official pages including abbreviations', async () => {
  for (const [question, sourceId] of [
    ['Xin giấy xác nhận sinh viên ở đâu?', 'faq-administrative-forms'],
    ['Tìm mẫu đơn bảo lưu kết quả học tập', 'faq-study-forms'],
    ['Cho em mẫu đơn xin vay vốn', 'faq-financial-support-forms'],
    ['dang ky ktx o dau', 'faq-dormitory-forms'],
    ['LMS của trường truy cập ở đâu?', 'faq-digital-directory'],
    ['Tìm giáo trình và sách điện tử', 'faq-library-directory'],
    ['Có chỗ hỗ trợ tâm lý cho sinh viên không?', 'faq-student-support-office'],
    ['Trường đăng tin tuyển dụng và thực tập ở đâu?', 'faq-career-directory'],
  ]) {
    const hits = await kb.search(question);
    assert.ok(
      hits.some((hit) => hit.citation.id === sourceId),
      `${question}: ${hits.map((h) => h.citation.id)}`,
    );
  }
});

test('topic change leaves grades behind while unanswered FAQ retains follow-up context', async () => {
  const changed = resolveQuestion('Vậy còn giấy xác nhận sinh viên thì sao?', [
    { role: 'assistant', text: 'Kết quả học tập', contextQuestion: 'Điểm của tôi' },
  ]);
  assert.equal(changed, 'Vậy còn giấy xác nhận sinh viên thì sao?');
  const model = new ModelFixture();
  const chat = new ChatService(db, kb, model);
  const answer = await chat.answer('Bãi gửi xe trường có mở ban đêm không?', guest);
  assert.equal(evidenceOf(model.calls.at(-1)!).kind, 'source_gap');
  await chat.answer('Vậy liên hệ ai?', guest, answer.conversationId);
  assert.ok(model.calls.at(-1)!.evidence.includes('missing_school_evidence'));
});

test('FAQ hints do not bypass record isolation or claim unsupported personal aid data', async () => {
  const model = new ModelFixture();
  const chat = new ChatService(db, kb, model);
  await chat.answer('Thủ tục xem hồ sơ của MOCK00019 ở đâu?', student, undefined, true);
  assert.equal(evidenceOf(model.calls.at(-1)!).kind, 'access_denied');
  const aid = STUDENT_FAQ_QUESTIONS.find(
    (q) => q.dataScope === 'personal' && q.categoryId === 'financial-aid',
  )!;
  const result = await chat.answer(aid.question, student, undefined, true);
  const call = model.calls.at(-1)!;
  assert.equal(evidenceOf(call).kind, 'personal');
  assert.equal(call.sensitivity, 'personal');
  assert.match(evidenceOf(call).facts, /Chưa có dữ liệu học bổng/);
  assert.equal(result.evaluations.length, 0);
});
