import type { LLMProvider, LLMRequest, LLMResponse } from '@nau/domain';

/** Mechanical test double only. It neither contacts nor evaluates a real AI model. */
export class ModelFixture implements LLMProvider {
  readonly mode = 'test-fixture';
  readonly calls: LLMRequest[] = [];
  constructor(
    private reply: (request: LLMRequest, index: number) => string = (_request, index) =>
      `Generated by the test-only model fixture: ${index + 1}.`,
  ) {}
  async generate(request: LLMRequest): Promise<LLMResponse> {
    request.signal?.throwIfAborted();
    const index = this.calls.push(request) - 1;
    const text = this.reply(request, index);
    request.signal?.throwIfAborted();
    request.onText?.(text);
    return {
      text,
      model: 'mechanical-test-fixture',
      inputTokens: 0,
      outputTokens: 0,
      costUsd: 0,
    };
  }
}

export function evidenceOf(request: LLMRequest): { kind: string; facts: any } {
  const evidence = JSON.parse(request.evidence);
  if (!evidence || typeof evidence.kind !== 'string' || !evidence.facts)
    throw new Error('Expected server-selected structured model evidence.');
  return evidence;
}

export function factsText(request: LLMRequest): string {
  const { facts } = evidenceOf(request);
  return typeof facts === 'string' ? facts : JSON.stringify(facts);
}
